application: impulserecreations
version: 1
runtime: php55
api_version: 1
threadsafe: false

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /imgs
  static_dir: imgs

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: index.php
